services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/tiktalk_db

  service-db:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "6432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped