services:
  backend:
    container_name: backend
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - postgres-tiktalk
      - minio
    env_file:
      - ./env.dev
    networks:
      - tiktalk-network

  postgres-tiktalk:
    container_name: postgres-tiktalk
    image: postgres:16
    ports:
      - "6432:5432"
    env_file:
      - ./env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tiktalk-network

  minio:
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - "9090:9090"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./data:/data
    command: minio server /data/minio --console-address ":9090"
    networks:
      - tiktalk-network

  keycloak-db:
    image: postgres:16
    container_name: keycloak_db
    environment:
      POSTGRES_USER: kcuser
      POSTGRES_PASSWORD: kcpassword
      POSTGRES_DB: keycloakdb
    ports:
    - "25432:5432"
    networks:
    - tiktalk-network
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloakdb
      KC_DB_USERNAME: kcuser
      KC_DB_PASSWORD: kcpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
     - "8180:8080"
    networks:
      - tiktalk-network

volumes:
  postgres-data: {}
  keycloak-data: {}

networks:
  tiktalk-network: { }