services:
#  client-backend:
#    image: app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8089:8089"
#    depends_on:
#      - postgres-tiktalk
#      - minio
#    env_file:
#      - ./env.dev
#    networks:
#      - backend-tiktalk

  postgres-tiktalk:
    image: postgres:16
    ports:
      - "6432:5432"

    env_file:
      - ./env.dev

    volumes:
      - postgres-tiktalk:/var/lib/postgres/data
    networks:
      - backend-tiktalk

  minio:
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9090:9090'
      - '9000:9000'
    env_file:
      - ./env.dev
    volumes:
      - minio:/data/minio
    networks:
      - backend-tiktalk
    command: minio server /data/minio --console-address ":9090"

    keycloak:
      image: quay.io/keycloak/keycloak:24.0.2
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak_db
        DB_USER: ${POSTGRES_USER:-postgres}
        DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin_password
      ports:
        - "8484:8484"
      depends_on:
        - keycloak-db
      networks:
        - backend-tiktalk

    keycloak-db:
      image: library/postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        POSTGRES_DB: keycloak_db
      ports:
        - "5432:5432"
      restart: unless-stopped


volumes:
  minio:
    driver: local
  postgres-tiktalk: { }

networks:
  backend-tiktalk: { }