services:
  client-backend:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - postgres-tiktalk
      - minio
    env_file:
      - ./env.dev
    networks:
      - backend-tiktalk

  postgres-tiktalk:
    image: postgres:16
    ports:
      - "6432:5432"

    env_file:
      - ./env.dev

    volumes:
      - postgres-tiktalk:/var/lib/postgres/data
    networks:
      - backend-tiktalk

  minio:
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9090:9090'
      - '9000:9000'
    env_file:
      - ./env.dev
    volumes:
      - minio:/data/minio
    networks:
      - backend-tiktalk
    command: minio server /data/minio --console-address ":9090"

volumes:
  minio:
    driver: local
  postgres-tiktalk: { }

networks:
  backend-tiktalk: { }