services:
  backend:
    container_name: backend
    hostname: backend
    image: ghcr.io/demiurge451/tiktalk_backend:fix-TT-126
    ports:
      - "8089:8089"
    depends_on:
      - postgres-tiktalk
      - minio
    env_file:
      - .env
    networks:
      - tiktalk-network

  postgres-tiktalk:
    container_name: postgres-tiktalk
    image: postgres:16
    ports:
      - "6432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tiktalk-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9090:9090"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server ~/minio --console-address :9090
    networks:
      - tiktalk-network

  keycloak-db:
    image: postgres:16
    container_name: keycloak_db
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: keycloakdb
    ports:
    - "25432:5432"
    networks:
    - tiktalk-network
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    hostname: keycloak
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloakdb
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    command:
      - "start-dev"
    ports:
     - "8180:8080"
    networks:
      - tiktalk-network

volumes:
  postgres-data: {}
  keycloak-data: {}
  minio-data: { }

networks:
  tiktalk-network:
    driver: bridge