services:
  postgres-tiktalk:
    container_name: tiktalk
    image: postgres:16
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: tiktalk_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-tiktalk:/var/lib/postgres/data
    networks:
      - backend-tiktalk

  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"

volumes:
  postgres-tiktalk: { }
  minio:
    driver: local

networks:
  backend-tiktalk: { }