server:
  port: 8080
  servlet:
    context-path: /tiktalk

spring:
  application:
    name: tiktalk_backend

  datasource:
    url: jdbc:postgresql://localhost:6432/tiktalk_db
    username: username
    password: password

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

minio:
  host: "http://127.0.0.1:9000"
  download-host: "http:/localhost:9000"
  user: root
  password: password
