server:
  port: 8089
  servlet:
    context-path: /tiktalk

spring:
  application:
    name: tiktalk_backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6432/tiktalk_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  keycloak:
    server-url: ${KEYCLOAK_HOST:http://localhost:8180}
    realm: tiktalk-realm
    username: ${KEYCLOAK_REALM_ADMIN_USERNAME}
    password: ${KEYCLOAK_REALM_ADMIN_PASSWORD}
    client-id: admin-cli
    grant-type: password

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUE_URI:http://localhost:8180/realms/tiktalk-realm}

logging:
  config: classpath:log4j2-plain.xml

minio:
  host: ${MINIO_HOST:http://127.0.0.1:9000}
  download-host: ${DOWNLOAD_HOST:http://localhost:9000}
  user: ${MINIO_ROOT_USER}
  password: ${MINIO_ROOT_PASSWORD}

springdoc:
  swagger-ui:
    oauth:
      client-id: clientback
      client-secret: ${SPRINGDOC_CLIENT_SECRET}