server:
  port: 8080
  servlet:
    context-path: /tiktalk

spring:
  application:
    name: tiktalk_backend

  datasource:
    url: jdbc:postgresql://localhost:6432/tiktalk_db
    username: username
    password: password

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
